region = "us-central1"
gcp_project = "cloudglobaldelivery-1000135575"
credentials= "credentials.json"
zookeepervpc = "default"
zookeepersub = "default"
instance_name = "zookeeper"
zookeeper_instance_ip_name = "zookeeperip"
zookeeper_instance_ip_region = "us-east1"
